// Which release of the game runs (USA, EUR or JPN), and its addresses. The runtime and its hook
// lists name game code and data by their USA addresses (the canonical ones); for the other releases
// tools/recomp/release_eur.txt and release_jpn.txt map them (generated by
// tools/recomp/port_addresses.py: the executables are the same program, shifted in places; hook
// addresses inside functions that differ are mapped one by one).
#pragma once
#include <cstdint>
#include <string>

namespace release {

enum class Id { USA, EUR, JPN };

// chooses the release from the executable's entry point; false if it is neither
bool select(uint32_t entryPoint);
Id id();
const char* name();           // "USA" / "EUR" / "JPN"
const char* name_of(Id id);
const char* name_of_entry(uint32_t entryPoint);  // "" if unknown
bool known_entry(uint32_t entryPoint);

// the running release's address of a USA code / data address (unchanged for USA; for code inside a
// function that differs between the releases: 0)
uint32_t code(uint32_t usa);
uint32_t data(uint32_t usa);
// the USA address of a code address of the running release (0 if it has none): function names
uint32_t usa_code(uint32_t addr);

// the address map's text of the release with this entry point ("" for USA; part of the code cache
// key: it decides the function names)
std::string map_text(uint32_t entryPoint);

// a USA address constant that reads as the running release's address
struct Code {
    uint32_t usa;
    operator uint32_t() const { return code(usa); }
};
struct Data {
    uint32_t usa;
    operator uint32_t() const { return data(usa); }
};

}  // namespace release
